### ISSUE TITLE
RuntimeError: storage has wrong size

### ISSUE THREAD

**Issue by bjchen666** [juntang-zhuang/ShelfNet-lw-cityscapes#1]
@juntang-zhuang 
When I run the training code, I always have the following problem.
```
Traceback (most recent call last):
  File "train.py", line 201, in <module>
    train()
  File "train.py", line 190, in train
    evaluate(checkpoint=save_pth)
  File "./evaluate.py", line 160, in evaluate
    net.load_state_dict(torch.load(save_pth))
  File "/home/dgs/anaconda2/envs/py3pytorch11/lib/python3.6/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/dgs/anaconda2/envs/py3pytorch11/lib/python3.6/site-packages/torch/serialization.py", line 581, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected 4325873720610324442 got 64
```

**Comment by juntang-zhuang** [comment]
@gshdong 
Hi, thanks for your interest. First please check if the file is correctly saved (by checking filesize for example). This might be a problem with distributed training, when torch.save() does not write into disk right away. I have not fully tested with distributed training on various systems or Pytorch versions.

This might be a conflict between distributed training and save the model directly from GPU (instead of first move the model to CPU then save). Note the difference in https://github.com/juntang-zhuang/ShelfNet-lw-cityscapes/blob/master/ShelfNet34_non_realtime/train.py#L164 and https://github.com/juntang-zhuang/ShelfNet-lw-cityscapes/blob/master/ShelfNet34_non_realtime/train.py#L171

One way to tackle this is, only save the file after the training is finished. Comment out https://github.com/juntang-zhuang/ShelfNet-lw-cityscapes/blob/master/ShelfNet34_non_realtime/train.py#L158 to https://github.com/juntang-zhuang/ShelfNet-lw-cityscapes/blob/master/ShelfNet34_non_realtime/train.py#L167 
To test if this saving works, you can set max_iter to a small number in https://github.com/juntang-zhuang/ShelfNet-lw-cityscapes/blob/master/ShelfNet34_non_realtime/train.py#L88 to check the saving. If it works, set it back to a large number.

**Comment by juntang-zhuang** [comment]
Maybe you can also move the model to cpu, save it, then move back to GPU. But I'm not sure if this will cause problems with distributed training
